name: verify-licensing-info
description: Verifies the licensing info for the current repository.
inputs:
  cargo-workspace:
    description: Set to true for working with a Cargo workspace repository.
    required: false
    default: false
  crates:
    description: >
      Use in conjunction with the `cargo-workspace` input to specify the crates to check for
      licensing. If `cargo-workspace` is set, this input must also be set. It should be a space
      separated string.
    required: false
    default: ''
  company-name:
    description: >
      The name of the company that should appear in the license file and copyright notices.
    required: true

runs:
  using: 'node16'
  main: 'index.js'
